version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: VecBot-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    env_file:
      - '.env'

  bot:
    container_name: VecBot
    restart: unless-stopped
    image: ghcr.io/vecnz/vecbot:main
    build: .
    env_file:
      - '.env'
    depends_on:
      - redis

volumes:
  redis:
